name: Tag main branch

on:
  push:
    branches:
      - prod

permissions:
  contents: write

jobs:
  tag-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Bump version
        uses: qzb/standard-version-action@v1.0.5
      - name: Push tag
        run: git push --follow-tags origin prod
        with:
          token: ${{ secrets.PAT }}