name: Tag main branch

on:
  push:
    branches:
      - prod

permissions:
  contents: write

jobs:
  tag-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Bump version
        uses: convention-change/action-standard-version@v1
        with:
          release-by-ref: ${{ github.ref }}
          push-changes-and-tag: true